# Site settings
title: "Dan Tilden: UX Designer" 
description: "Portfolio for Dan Tilden"
baseurl: ""
url: ""
twitter_username: freakified
github_username:  tilden

# Build settings
permalink: pretty
