# Site settings
title: DanTilden.com
description: "Portfolio for Dan Tilden"
baseurl: ""
url: ""
twitter_username: freakified
github_username:  tilden

# Build settings
markdown: kramdown
permalink: pretty
