# Site settings
title: "Dan Tilden: UX Designer" 
description: "Portfolio for Dan Tilden"
baseurl: ""
url: ""
twitter_username: freakified
github_username:  tilden

# Build settings
permalink: pretty

# Sass settings
sass:
    sass_dir: _sass
    style: nested

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
      section: "blog"
      top_bar_color: "#EF6C00"
  -
    scope: 
      path: "projects"
      type: "pages"
    values:
      section: "portfolio"
